# Generated by Django 4.2.5 on 2023-09-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='idade',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
